import { BookModel } from 'impactdisciplescommon/src/books/models/book.model';
import { I18Model, TranslationsService } from 'impactdisciplescommon/src/books/services/lesson-language.service';
import { Injectable } from '@angular/core';
import { LessonModel } from '../models/lesson.model';
import { BaseService } from './base.service';
import { FirebaseDAO } from './firebase.dao';

@Injectable({
  providedIn: 'root'
})
export class LessonService extends BaseService<LessonModel>{
  constructor(public override dao: FirebaseDAO<LessonModel>, private translationsService: TranslationsService) {
    super(dao)
    this.table="lessons"
  }

  addHeaderField(form, lesson: LessonModel, book: BookModel, renderOptions: I18Model){
    if(lesson.goal){
      form['components'].unshift(
        {
          "html": "<p><strong>" + this.translationsService.translate('Goal', renderOptions) + ":</strong> "+this.translationsService.translate(lesson.goal, renderOptions)+"</p>",
          "label": "Content",
          "refreshOnChange": false,
          "key": "content4",
          "type": "content",
          "input": false,
          "tableView": false,
          "id": "effcjwx",
          "placeholder": "",
          "prefix": "",
          "customClass": "",
          "suffix": "",
          "multiple": false,
          "defaultValue": null,
          "protected": false,
          "unique": false,
          "persistent": true,
          "hidden": false,
          "clearOnHide": true,
          "refreshOn": "",
          "redrawOn": "",
          "modalEdit": false,
          "dataGridLabel": false,
          "labelPosition": "top",
          "description": "",
          "errorLabel": "",
          "tooltip": "",
          "hideLabel": false,
          "tabindex": "",
          "disabled": false,
          "autofocus": false,
          "dbIndex": false,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "widget": null,
          "attributes": {},
          "validateOn": "change",
          "validate": {
            "required": false,
            "custom": "",
            "customPrivate": false,
            "strictDateValidation": false,
            "multiple": false,
            "unique": false
          },
          "conditional": { "show": null, "when": null, "eq": "" },
          "overlay": {
            "style": "",
            "left": "",
            "top": "",
            "width": "",
            "height": ""
          },
          "allowCalculateOverride": false,
          "encrypted": false,
          "showCharCount": false,
          "showWordCount": false,
          "properties": {},
          "allowMultipleMasks": false,
          "addons": []
        }
      )
    }

    if(lesson.memoryVerse){
      form['components'].unshift(
        {
          "html": "<p><strong>" + this.translationsService.translate('Memory Verse', renderOptions) + ":</strong> "+this.translationsService.translate(lesson.memoryVerse, renderOptions)+"</p>",
          "label": "Content",
          "customClass": "",
          "refreshOnChange": false,
          "hidden": false,
          "modalEdit": false,
          "key": "content6",
          "tags": [],
          "properties": {},
          "conditional": {
            "show": null,
            "when": null,
            "eq": "",
            "json": ""
          },
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "overlay": {
            "style": "",
            "page": "",
            "left": "",
            "top": "",
            "width": "",
            "height": ""
          },
          "type": "content",
          "input": false,
          "tableView": false,
          "placeholder": "",
          "prefix": "",
          "suffix": "",
          "multiple": false,
          "defaultValue": null,
          "protected": false,
          "unique": false,
          "persistent": true,
          "clearOnHide": true,
          "refreshOn": "",
          "redrawOn": "",
          "labelPosition": "top",
          "description": "",
          "errorLabel": "",
          "tooltip": "",
          "hideLabel": false,
          "tabindex": "",
          "disabled": false,
          "autofocus": false,
          "dbIndex": false,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "widget": null,
          "validateOn": "change",
          "validate": {
            "required": false,
            "custom": "",
            "customPrivate": false,
            "strictDateValidation": false,
            "multiple": false,
            "unique": false
          },
          "allowCalculateOverride": false,
          "encrypted": false,
          "showCharCount": false,
          "showWordCount": false,
          "allowMultipleMasks": false,
          "addons": [],
          "id": "eumawcb",
          "dataGridLabel": false
        }
      )
    }

    form['components'].unshift(
      {
          "html": "<p style=\"text-align:center;\"><span class=\"text-big\"><strong>" + this.translationsService.translate(lesson.title, renderOptions) +"</strong></span></p>",
          "label": "Content",
          "customClass": "",
          "refreshOnChange": false,
          "hidden": false,
          "modalEdit": false,
          "key": "lessonTitle",
          "tags": [],
          "properties": {},
          "conditional": { "show": null, "when": null, "eq": "", "json": "" },
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "overlay": {
            "style": "",
            "page": "",
            "left": "",
            "top": "",
            "width": "",
            "height": ""
          },
          "type": "content",
          "input": false,
          "placeholder": "",
          "prefix": "",
          "suffix": "",
          "multiple": false,
          "defaultValue": null,
          "protected": false,
          "unique": false,
          "persistent": true,
          "clearOnHide": true,
          "refreshOn": "",
          "redrawOn": "",
          "tableView": false,
          "labelPosition": "top",
          "description": "",
          "errorLabel": "",
          "tooltip": "",
          "hideLabel": false,
          "tabindex": "",
          "disabled": false,
          "autofocus": false,
          "dbIndex": false,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "widget": null,
          "validateOn": "change",
          "validate": {
            "required": false,
            "custom": "",
            "customPrivate": false,
            "strictDateValidation": false,
            "multiple": false,
            "unique": false
          },
          "allowCalculateOverride": false,
          "encrypted": false,
          "showCharCount": false,
          "showWordCount": false,
          "allowMultipleMasks": false,
          "addons": [],
          "id": "ek7krw",
          "dataGridLabel": false
      }
    )

    form['components'].unshift(
      {
        "html": "<p style=\"text-align:center;\"><span class=\"text-big\"><strong>" + this.translationsService.translate(book.title, renderOptions) + "</strong></span></p>",
        "label": "Content",
        "customClass": "",
        "refreshOnChange": false,
        "hidden": false,
        "modalEdit": false,
        "key": "bookTitle",
        "tags": [],
        "properties": {},
        "conditional": { "show": null, "when": null, "eq": "", "json": "" },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "content",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": true,
        "clearOnHide": true,
        "refreshOn": "",
        "redrawOn": "",
        "tableView": false,
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "hideLabel": false,
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "calculateServer": false,
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false,
          "multiple": false,
          "unique": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "addons": [],
        "id": "eusyc3",
        "dataGridLabel": false
      }
    )

    return form;
  }

  addDailyReadings(form, lesson: LessonModel, renderOptions: I18Model){
    let tabs = form['components'].find(component => component['label'] == 'Tabs');

    tabs['components'].push(
        {
          "label": "Daily Readings",
          "key": "prayerRequests",
          "components": [
            {
              "html": "<p><strong>" + this.translationsService.translate('Weekly Bible Reading', renderOptions) + "</strong></p>",
              "label": "Content",
              "refreshOnChange": false,
              "key": "content31",
              "type": "content",
              "input": false,
              "tableView": false,
              "id": "e0bdleh",
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "widget": null,
              "attributes": {},
              "validateOn": "change",
              "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "conditional": { "show": null, "when": null, "eq": "" },
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": {},
              "allowMultipleMasks": false,
              "addons": []
            },
            {
              "label": "Columns",
              "columns": [
                {
                  "components": [
                    {
                        "label": "Introduction",
                        "key": "introduction",
                        "type": "well",
                        "input": false,
                        "tableView": false,
                        "components": [
                          {
                              "html": "<p>" + this.translationsService.translate('Read the passage and write an insight on at least one of the following:', renderOptions) + "</p>",
                              "label": "Content",
                              "refreshOnChange": false,
                              "key": "content32",
                              "type": "content",
                              "input": false,
                              "tableView": false,
                              "id": "e18bnye",
                              "placeholder": "",
                              "prefix": "",
                              "customClass": "",
                              "suffix": "",
                              "multiple": false,
                              "defaultValue": null,
                              "protected": false,
                              "unique": false,
                              "persistent": true,
                              "hidden": false,
                              "clearOnHide": true,
                              "refreshOn": "",
                              "redrawOn": "",
                              "modalEdit": false,
                              "dataGridLabel": false,
                              "labelPosition": "top",
                              "description": "",
                              "errorLabel": "",
                              "tooltip": "",
                              "hideLabel": false,
                              "tabindex": "",
                              "disabled": false,
                              "autofocus": false,
                              "dbIndex": false,
                              "customDefaultValue": "",
                              "calculateValue": "",
                              "calculateServer": false,
                              "widget": null,
                              "attributes": {},
                              "validateOn": "change",
                              "validate": {
                                "required": false,
                                "custom": "",
                                "customPrivate": false,
                                "strictDateValidation": false,
                                "multiple": false,
                                "unique": false
                              },
                              "conditional": { "show": null, "when": null, "eq": "" },
                              "overlay": {
                                "style": "",
                                "left": "",
                                "top": "",
                                "width": "",
                                "height": ""
                              },
                              "allowCalculateOverride": false,
                              "encrypted": false,
                              "showCharCount": false,
                              "showWordCount": false,
                              "properties": {},
                              "allowMultipleMasks": false,
                              "addons": []
                          },
                          {
                            "html": "<p><strong>A</strong>: Attitude to Change</p>",
                            "label": "Content",
                            "refreshOnChange": false,
                            "key": "content33",
                            "type": "content",
                            "input": false,
                            "tableView": false,
                            "id": "elqjdp",
                            "placeholder": "",
                            "prefix": "",
                            "customClass": "",
                            "suffix": "",
                            "multiple": false,
                            "defaultValue": null,
                            "protected": false,
                            "unique": false,
                            "persistent": true,
                            "hidden": false,
                            "clearOnHide": true,
                            "refreshOn": "",
                            "redrawOn": "",
                            "modalEdit": false,
                            "dataGridLabel": false,
                            "labelPosition": "top",
                            "description": "",
                            "errorLabel": "",
                            "tooltip": "",
                            "hideLabel": false,
                            "tabindex": "",
                            "disabled": false,
                            "autofocus": false,
                            "dbIndex": false,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "calculateServer": false,
                            "widget": null,
                            "attributes": {},
                            "validateOn": "change",
                            "validate": {
                              "required": false,
                              "custom": "",
                              "customPrivate": false,
                              "strictDateValidation": false,
                              "multiple": false,
                              "unique": false
                            },
                            "conditional": { "show": null, "when": null, "eq": "" },
                            "overlay": {
                              "style": "",
                              "left": "",
                              "top": "",
                              "width": "",
                              "height": ""
                            },
                            "allowCalculateOverride": false,
                            "encrypted": false,
                            "showCharCount": false,
                            "showWordCount": false,
                            "properties": {},
                            "allowMultipleMasks": false,
                            "addons": []
                          },
                          {
                            "html": "<p><strong>C</strong>: Command to Obey</p>",
                            "label": "Content",
                            "refreshOnChange": false,
                            "key": "content34",
                            "type": "content",
                            "input": false,
                            "tableView": false,
                            "id": "ehkz9lf",
                            "placeholder": "",
                            "prefix": "",
                            "customClass": "",
                            "suffix": "",
                            "multiple": false,
                            "defaultValue": null,
                            "protected": false,
                            "unique": false,
                            "persistent": true,
                            "hidden": false,
                            "clearOnHide": true,
                            "refreshOn": "",
                            "redrawOn": "",
                            "modalEdit": false,
                            "dataGridLabel": false,
                            "labelPosition": "top",
                            "description": "",
                            "errorLabel": "",
                            "tooltip": "",
                            "hideLabel": false,
                            "tabindex": "",
                            "disabled": false,
                            "autofocus": false,
                            "dbIndex": false,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "calculateServer": false,
                            "widget": null,
                            "attributes": {},
                            "validateOn": "change",
                            "validate": {
                              "required": false,
                              "custom": "",
                              "customPrivate": false,
                              "strictDateValidation": false,
                              "multiple": false,
                              "unique": false
                            },
                            "conditional": { "show": null, "when": null, "eq": "" },
                            "overlay": {
                              "style": "",
                              "left": "",
                              "top": "",
                              "width": "",
                              "height": ""
                            },
                            "allowCalculateOverride": false,
                            "encrypted": false,
                            "showCharCount": false,
                            "showWordCount": false,
                            "properties": {},
                            "allowMultipleMasks": false,
                            "addons": []
                          },
                          {
                            "html": "<p><strong>T</strong>: Truth to Believe</p>",
                            "label": "Content",
                            "refreshOnChange": false,
                            "key": "content35",
                            "type": "content",
                            "input": false,
                            "tableView": false,
                            "id": "e6kz82p",
                            "placeholder": "",
                            "prefix": "",
                            "customClass": "",
                            "suffix": "",
                            "multiple": false,
                            "defaultValue": null,
                            "protected": false,
                            "unique": false,
                            "persistent": true,
                            "hidden": false,
                            "clearOnHide": true,
                            "refreshOn": "",
                            "redrawOn": "",
                            "modalEdit": false,
                            "dataGridLabel": false,
                            "labelPosition": "top",
                            "description": "",
                            "errorLabel": "",
                            "tooltip": "",
                            "hideLabel": false,
                            "tabindex": "",
                            "disabled": false,
                            "autofocus": false,
                            "dbIndex": false,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "calculateServer": false,
                            "widget": null,
                            "attributes": {},
                            "validateOn": "change",
                            "validate": {
                              "required": false,
                              "custom": "",
                              "customPrivate": false,
                              "strictDateValidation": false,
                              "multiple": false,
                              "unique": false
                            },
                            "conditional": { "show": null, "when": null, "eq": "" },
                            "overlay": {
                              "style": "",
                              "left": "",
                              "top": "",
                              "width": "",
                              "height": ""
                            },
                            "allowCalculateOverride": false,
                            "encrypted": false,
                            "showCharCount": false,
                            "showWordCount": false,
                            "properties": {},
                            "allowMultipleMasks": false,
                            "addons": []
                          },
                          {
                            "html": "<p><strong>S</strong>: Sin to Confess</p>",
                            "label": "Content",
                            "refreshOnChange": false,
                            "key": "content36",
                            "type": "content",
                            "input": false,
                            "tableView": false,
                            "id": "e5ey7fi",
                            "placeholder": "",
                            "prefix": "",
                            "customClass": "",
                            "suffix": "",
                            "multiple": false,
                            "defaultValue": null,
                            "protected": false,
                            "unique": false,
                            "persistent": true,
                            "hidden": false,
                            "clearOnHide": true,
                            "refreshOn": "",
                            "redrawOn": "",
                            "modalEdit": false,
                            "dataGridLabel": false,
                            "labelPosition": "top",
                            "description": "",
                            "errorLabel": "",
                            "tooltip": "",
                            "hideLabel": false,
                            "tabindex": "",
                            "disabled": false,
                            "autofocus": false,
                            "dbIndex": false,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "calculateServer": false,
                            "widget": null,
                            "attributes": {},
                            "validateOn": "change",
                            "validate": {
                              "required": false,
                              "custom": "",
                              "customPrivate": false,
                              "strictDateValidation": false,
                              "multiple": false,
                              "unique": false
                            },
                            "conditional": { "show": null, "when": null, "eq": "" },
                            "overlay": {
                              "style": "",
                              "left": "",
                              "top": "",
                              "width": "",
                              "height": ""
                            },
                            "allowCalculateOverride": false,
                            "encrypted": false,
                            "showCharCount": false,
                            "showWordCount": false,
                            "properties": {},
                            "allowMultipleMasks": false,
                            "addons": []
                          }
                        ]
                    }

                  ],
                  "width": 7,
                  "offset": 0,
                  "push": 0,
                  "pull": 0,
                  "size": "md",
                  "currentWidth": 6
                },
                {
                  "components": [
                    {
                      "label": "Introduction",
                      "key": "introduction",
                      "type": "well",
                      "input": false,
                      "tableView": false,
                      "components": [
                        {
                          "html": "<p><strong>" + this.translationsService.translate('Monday', renderOptions) + ":</strong> " + this.translationsService.translate(lesson.monVerse, renderOptions) + "</p>",
                          "label": "Content",
                          "refreshOnChange": false,
                          "key": "monVerse",
                          "type": "content",
                          "input": false,
                          "tableView": false,
                          "id": "ej1fnmg",
                          "placeholder": "",
                          "prefix": "",
                          "customClass": "",
                          "suffix": "",
                          "multiple": false,
                          "defaultValue": null,
                          "protected": false,
                          "unique": false,
                          "persistent": true,
                          "hidden": false,
                          "clearOnHide": true,
                          "refreshOn": "",
                          "redrawOn": "",
                          "modalEdit": false,
                          "dataGridLabel": false,
                          "labelPosition": "top",
                          "description": "",
                          "errorLabel": "",
                          "tooltip": "",
                          "hideLabel": false,
                          "tabindex": "",
                          "disabled": false,
                          "autofocus": false,
                          "dbIndex": false,
                          "customDefaultValue": "",
                          "calculateValue": "",
                          "calculateServer": false,
                          "widget": null,
                          "attributes": {},
                          "validateOn": "change",
                          "validate": {
                            "required": false,
                            "custom": "",
                            "customPrivate": false,
                            "strictDateValidation": false,
                            "multiple": false,
                            "unique": false
                          },
                          "conditional": { "show": null, "when": null, "eq": "" },
                          "overlay": {
                            "style": "",
                            "left": "",
                            "top": "",
                            "width": "",
                            "height": ""
                          },
                          "allowCalculateOverride": false,
                          "encrypted": false,
                          "showCharCount": false,
                          "showWordCount": false,
                          "properties": {},
                          "allowMultipleMasks": false,
                          "addons": []
                        },
                        {
                          "html": "<p><strong>" + this.translationsService.translate('Tuesday', renderOptions) + ":</strong> " + this.translationsService.translate(lesson.tueVerse, renderOptions) + "</p>",
                          "label": "Content",
                          "refreshOnChange": false,
                          "key": "tueVerse",
                          "type": "content",
                          "input": false,
                          "tableView": false,
                          "id": "epniemp",
                          "placeholder": "",
                          "prefix": "",
                          "customClass": "",
                          "suffix": "",
                          "multiple": false,
                          "defaultValue": null,
                          "protected": false,
                          "unique": false,
                          "persistent": true,
                          "hidden": false,
                          "clearOnHide": true,
                          "refreshOn": "",
                          "redrawOn": "",
                          "modalEdit": false,
                          "dataGridLabel": false,
                          "labelPosition": "top",
                          "description": "",
                          "errorLabel": "",
                          "tooltip": "",
                          "hideLabel": false,
                          "tabindex": "",
                          "disabled": false,
                          "autofocus": false,
                          "dbIndex": false,
                          "customDefaultValue": "",
                          "calculateValue": "",
                          "calculateServer": false,
                          "widget": null,
                          "attributes": {},
                          "validateOn": "change",
                          "validate": {
                            "required": false,
                            "custom": "",
                            "customPrivate": false,
                            "strictDateValidation": false,
                            "multiple": false,
                            "unique": false
                          },
                          "conditional": { "show": null, "when": null, "eq": "" },
                          "overlay": {
                            "style": "",
                            "left": "",
                            "top": "",
                            "width": "",
                            "height": ""
                          },
                          "allowCalculateOverride": false,
                          "encrypted": false,
                          "showCharCount": false,
                          "showWordCount": false,
                          "properties": {},
                          "allowMultipleMasks": false,
                          "addons": []
                        },
                        {
                          "html": "<p><strong>" + this.translationsService.translate('Wednesday', renderOptions) + ":</strong> " + this.translationsService.translate(lesson.wedVerse, renderOptions) + "</p>",
                          "label": "Content",
                          "refreshOnChange": false,
                          "key": "wedVerse",
                          "type": "content",
                          "input": false,
                          "tableView": false,
                          "id": "eemiufc",
                          "placeholder": "",
                          "prefix": "",
                          "customClass": "",
                          "suffix": "",
                          "multiple": false,
                          "defaultValue": null,
                          "protected": false,
                          "unique": false,
                          "persistent": true,
                          "hidden": false,
                          "clearOnHide": true,
                          "refreshOn": "",
                          "redrawOn": "",
                          "modalEdit": false,
                          "dataGridLabel": false,
                          "labelPosition": "top",
                          "description": "",
                          "errorLabel": "",
                          "tooltip": "",
                          "hideLabel": false,
                          "tabindex": "",
                          "disabled": false,
                          "autofocus": false,
                          "dbIndex": false,
                          "customDefaultValue": "",
                          "calculateValue": "",
                          "calculateServer": false,
                          "widget": null,
                          "attributes": {},
                          "validateOn": "change",
                          "validate": {
                            "required": false,
                            "custom": "",
                            "customPrivate": false,
                            "strictDateValidation": false,
                            "multiple": false,
                            "unique": false
                          },
                          "conditional": { "show": null, "when": null, "eq": "" },
                          "overlay": {
                            "style": "",
                            "left": "",
                            "top": "",
                            "width": "",
                            "height": ""
                          },
                          "allowCalculateOverride": false,
                          "encrypted": false,
                          "showCharCount": false,
                          "showWordCount": false,
                          "properties": {},
                          "allowMultipleMasks": false,
                          "addons": []
                        },
                        {
                          "html": "<p><strong>" + this.translationsService.translate('Thursday', renderOptions) + ":</strong> " + this.translationsService.translate(lesson.thuVerse, renderOptions) + "</p>",
                          "label": "Content",
                          "refreshOnChange": false,
                          "key": "thuVerse",
                          "type": "content",
                          "input": false,
                          "tableView": false,
                          "id": "e1g074j",
                          "placeholder": "",
                          "prefix": "",
                          "customClass": "",
                          "suffix": "",
                          "multiple": false,
                          "defaultValue": null,
                          "protected": false,
                          "unique": false,
                          "persistent": true,
                          "hidden": false,
                          "clearOnHide": true,
                          "refreshOn": "",
                          "redrawOn": "",
                          "modalEdit": false,
                          "dataGridLabel": false,
                          "labelPosition": "top",
                          "description": "",
                          "errorLabel": "",
                          "tooltip": "",
                          "hideLabel": false,
                          "tabindex": "",
                          "disabled": false,
                          "autofocus": false,
                          "dbIndex": false,
                          "customDefaultValue": "",
                          "calculateValue": "",
                          "calculateServer": false,
                          "widget": null,
                          "attributes": {},
                          "validateOn": "change",
                          "validate": {
                            "required": false,
                            "custom": "",
                            "customPrivate": false,
                            "strictDateValidation": false,
                            "multiple": false,
                            "unique": false
                          },
                          "conditional": { "show": null, "when": null, "eq": "" },
                          "overlay": {
                            "style": "",
                            "left": "",
                            "top": "",
                            "width": "",
                            "height": ""
                          },
                          "allowCalculateOverride": false,
                          "encrypted": false,
                          "showCharCount": false,
                          "showWordCount": false,
                          "properties": {},
                          "allowMultipleMasks": false,
                          "addons": []
                        },
                        {
                          "html": "<p><strong>" + this.translationsService.translate('Friday', renderOptions) + ":</strong> " + this.translationsService.translate(lesson.friVerse, renderOptions) + "</p>",
                          "label": "Content",
                          "refreshOnChange": false,
                          "key": "friVerse",
                          "type": "content",
                          "input": false,
                          "tableView": false,
                          "id": "e01r9h",
                          "placeholder": "",
                          "prefix": "",
                          "customClass": "",
                          "suffix": "",
                          "multiple": false,
                          "defaultValue": null,
                          "protected": false,
                          "unique": false,
                          "persistent": true,
                          "hidden": false,
                          "clearOnHide": true,
                          "refreshOn": "",
                          "redrawOn": "",
                          "modalEdit": false,
                          "dataGridLabel": false,
                          "labelPosition": "top",
                          "description": "",
                          "errorLabel": "",
                          "tooltip": "",
                          "hideLabel": false,
                          "tabindex": "",
                          "disabled": false,
                          "autofocus": false,
                          "dbIndex": false,
                          "customDefaultValue": "",
                          "calculateValue": "",
                          "calculateServer": false,
                          "widget": null,
                          "attributes": {},
                          "validateOn": "change",
                          "validate": {
                            "required": false,
                            "custom": "",
                            "customPrivate": false,
                            "strictDateValidation": false,
                            "multiple": false,
                            "unique": false
                          },
                          "conditional": { "show": null, "when": null, "eq": "" },
                          "overlay": {
                            "style": "",
                            "left": "",
                            "top": "",
                            "width": "",
                            "height": ""
                          },
                          "allowCalculateOverride": false,
                          "encrypted": false,
                          "showCharCount": false,
                          "showWordCount": false,
                          "properties": {},
                          "allowMultipleMasks": false,
                          "addons": []
                        }
                      ]
                    }
                  ],
                  "width": 5,
                  "offset": 0,
                  "push": 0,
                  "pull": 0,
                  "size": "md",
                  "currentWidth": 6
                }
              ],
              "key": "columns",
              "type": "columns",
              "input": false,
              "tableView": false,
              "id": "eg9451j",
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": false,
              "hidden": false,
              "clearOnHide": false,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "widget": null,
              "attributes": {},
              "validateOn": "change",
              "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "conditional": { "show": null, "when": null, "eq": "" },
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": {},
              "allowMultipleMasks": false,
              "addons": [],
              "tree": false,
              "lazyLoad": false,
              "autoAdjust": false
            }
          ]
        }
    )
  }
}
